Progect Spring - 8
EvgeniiVarlakhov/java-filmorate pull request #1
Opened 2022-07-23 13:28 UTC by EvgeniiVarlakhov

Выполнено задание ТЗ-8.

2022-07-24 08:09 UTC, kukolev requested changes

2022-07-24 08:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-07-24 08:09 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-07-24 08:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(UserController.class);
Лучше использовать аннотацию @Slf4j, тогда логгер будет создавать автоматически фреймворком и не нужно будет писать однотипный код в каждом классе. Подробнее можно почитать тут: https://www.baeldung.com/slf4j-with-log4j2-logback

2022-07-24 08:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final static Logger log = LoggerFactory.getLogger(UserController.class);
Лучше использовать аннотацию @Slf4j, тогда логгер будет создавать автоматически фреймворком и не нужно будет писать однотипный код в каждом классе. Подробнее можно почитать тут: https://www.baeldung.com/slf4j-with-log4j2-logback

2022-07-24 08:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-07-24 09:50 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Выполнено.

2022-07-24 09:50 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Выполнено.

2022-07-24 09:50 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(UserController.class);
Выполнено.

2022-07-24 09:50 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final static Logger log = LoggerFactory.getLogger(UserController.class);
Выполнено.

2022-07-24 09:50 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Выполнено.

2022-07-24 17:06 UTC, kukolev requested changes
В ПР не попали исправления табов на пробелы в классе приложения и в тесте. Нужно добавить эти исправления.

2022-07-25 07:22 UTC, kukolev approved these changes

2022-07-25 10:01 UTC, merged