fix:выполнить спринт-9.
EvgeniiVarlakhov/java-filmorate pull request #2
Opened 2022-08-01 19:55 UTC by EvgeniiVarlakhov

Выполнено ТЗ-9. Добавлен новый функционал.

2022-08-02 17:16 UTC, kukolev requested changes

2022-08-02 17:16 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validated(Film film) throws InvalidValidationException {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-08-02 17:16 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void validated(User user) throws InvalidValidationException {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-08-02 17:16 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error("ООшибка при удалении лайка.Пользователя с таким ID не существует.'{}'", idUser);
Орфографическая ошибка в слове «ООШибка». Нужно исправить.

2022-08-02 17:16 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error("Ошибка при обновлении фильма.Фильма с таким ID не существует.'{}'", film.getId());
Здесь и ниже нужны пробелы после «.»

2022-08-02 17:32 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error("ООшибка при удалении лайка.Пользователя с таким ID не существует.'{}'", idUser);
Исправлено

2022-08-02 17:35 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error("Ошибка при обновлении фильма.Фильма с таким ID не существует.'{}'", film.getId());
Исправлено.

2022-08-02 17:48 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validated(Film film) throws InvalidValidationException {
Исправлено на validateFilm.

2022-08-02 17:48 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void validated(User user) throws InvalidValidationException {
Исправлено на validateUser.

2022-08-03 07:41 UTC, kukolev requested changes

2022-08-03 07:41 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final LocalDate VALIDDATE = LocalDate.of(1895, 12, 28);
Судя по всему это константа. Константы должны быть объявлены как static.

2022-08-03 08:01 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final LocalDate VALIDDATE = LocalDate.of(1895, 12, 28);
Исправлено.

2022-08-03 16:36 UTC, kukolev approved these changes

2022-08-03 17:20 UTC, merged