Спринт 10-11.
EvgeniiVarlakhov/java-filmorate pull request #3
Opened 2022-08-12 13:58 UTC by EvgeniiVarlakhov

Выполнен спринт 10-11.

2022-08-12 16:44 UTC, kukolev requested changes

2022-08-12 16:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +        film.setMpa(new MpaRating(rs.getInt("MPA_RATING.mpa_id"), rs.getString("MPA_RATING.mpa_name"), rs.getString("MPA_RATING.description")));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-12 16:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/comparator/FilmLikesComparator.java
> +        return 1; //Integer.compare(film2.getLikes().size(), film1.getLikes().size());
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-13 06:51 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/comparator/FilmLikesComparator.java
> +        return 1; //Integer.compare(film2.getLikes().size(), film1.getLikes().size());
Исправлено. Не использованный код удален.

2022-08-13 06:54 UTC, EvgeniiVarlakhov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +        film.setMpa(new MpaRating(rs.getInt("MPA_RATING.mpa_id"), rs.getString("MPA_RATING.mpa_name"), rs.getString("MPA_RATING.description")));
Исправлено.

2022-08-14 07:20 UTC, kukolev requested changes

2022-08-14 07:20 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testUserDbStorage() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 07:20 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testFriendDbStorage() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 07:20 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testGenreDbStorage() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 07:20 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testLikeDbStorage() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 07:20 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testMpaRatingDbStorage() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 07:20 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testFilmDbStorage() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 09:22 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testUserDbStorage() {
Выполнено.

2022-08-14 09:22 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testFriendDbStorage() {
Выполнено.

2022-08-14 09:22 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testGenreDbStorage() {
Выполнено.

2022-08-14 09:22 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testLikeDbStorage() {
Выполнено.

2022-08-14 09:23 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testMpaRatingDbStorage() {
Выполнено.

2022-08-14 09:23 UTC, EvgeniiVarlakhov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void testFilmDbStorage() {
Выполнено.

2022-08-14 21:45 UTC, kukolev approved these changes

2022-08-15 02:39 UTC, merged